# Phase 7J — local TLS trust fix, environment-only, no discovery/provider
# logic touched. Root cause (diagnosed, not guessed): this machine's Avast
# Antivirus performs HTTPS-scanning by locally re-signing every TLS
# connection (including api.explorium.ai) with a self-generated root CA
# ("Avast Web/Mail Shield Root, generated by Avast Antivirus for SSL/TLS
# scanning"). That root is installed into and trusted by the Windows
# certificate store, but Python's default TLS verification (via httpx ->
# certifi's fixed, vendored CA bundle) never consults the OS store, so
# every real outbound HTTPS call from this app (Explorium, Apollo, and
# Unipile alike — confirmed all three providers use httpx) fails with
# CERTIFICATE_VERIFY_FAILED before reaching the provider at all.
#
# truststore (PyPA-maintained: https://github.com/sethmlarson/truststore)
# makes Python's ssl.SSLContext delegate verification to the OS-native
# trust store (Windows SChannel here) instead of certifi's bundle — this
# is verification working correctly against a locally, legitimately
# trusted root, not a bypass: certificate checking stays fully enabled,
# nothing is hardcoded, and no application/discovery/provider code changes.
# Must run before any module constructs an ssl.SSLContext or httpx client
# (see truststore's own documented usage), hence first import in the
# process entrypoint.
import truststore

truststore.inject_into_ssl()

import logging
from contextlib import asynccontextmanager

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from app.api import (
    adversarial_review,
    batch,
    business_model,
    commercial_signal,
    companies,
    company_quality,
    discovery,
    discovery_providers,
    evidence,
    export,
    feedback,
    feedback_learning,
    field_verification,
    hard_icp_validation,
    health,
    human_review,
    icps,
    lead_confidence,
    lead_deduplication,
    llm_qualification,
    optimization,
    optimization_application,
    people,
    people_discovery,
    pipeline,
    provider_routing,
    provider_usage,
    ranking,
    scoring,
)
from app.core.config import get_settings
from app.db.session import init_db

logger = logging.getLogger(__name__)


@asynccontextmanager
async def lifespan(app: FastAPI):
    try:
        init_db()
    except Exception as exc:  # pragma: no cover - depends on local DB availability
        logger.warning("Database unavailable at startup (%s); ICP endpoints will fail until it is reachable.", exc)
    yield


def create_app() -> FastAPI:
    settings = get_settings()

    app = FastAPI(
        title=settings.app_name,
        description="AI-powered ICP Lead Research & Qualification Platform.",
        version="0.1.0",
        lifespan=lifespan,
    )

    app.add_middleware(
        CORSMiddleware,
        allow_origins=settings.cors_origins,
        allow_credentials=True,
        allow_methods=["*"],
        allow_headers=["*"],
    )

    app.include_router(health.router)
    app.include_router(icps.router)
    app.include_router(feedback.router)
    app.include_router(discovery.router)
    app.include_router(companies.router)
    app.include_router(company_quality.router)
    app.include_router(people_discovery.router)
    app.include_router(people.router)
    app.include_router(evidence.router)
    app.include_router(hard_icp_validation.router)
    app.include_router(business_model.router)
    app.include_router(commercial_signal.router)
    app.include_router(scoring.router)
    app.include_router(llm_qualification.router)
    app.include_router(adversarial_review.router)
    app.include_router(field_verification.router)
    app.include_router(lead_deduplication.router)
    app.include_router(lead_deduplication.leads_router)
    app.include_router(human_review.router)
    app.include_router(batch.router)
    app.include_router(ranking.router)
    app.include_router(export.router)
    app.include_router(feedback_learning.router)
    app.include_router(optimization.router)
    app.include_router(optimization_application.router)
    app.include_router(provider_routing.router)
    app.include_router(provider_usage.router)
    app.include_router(discovery_providers.router)
    app.include_router(lead_confidence.router)
    app.include_router(pipeline.router)

    return app


app = create_app()
